<?php
/** @var $block Template */

use Magento\Backend\Block\Template;
use Yireo\DeleteAnyOrder2\ViewModel\Fixer as FixerViewModel;

/** @var FixerViewModel $viewModel */
$viewModel = $block->getFixerViewModel();
$tables = $viewModel->getTables();
?>
<div class="admin__data-grid-wrap">
    <table class="data-grid">
        <thead>
        <th class="data-grid-th">
            <span class="data-grid-cell-content"><?= $block->escapeHtml(__('Database Table')) ?></span>
        </th>
        <th class="data-grid-th">
            <span class="data-grid-cell-content"><?= $block->escapeHtml(__('Total Records')) ?></span>
        </th>
        <th class="data-grid-th">
            <span class="data-grid-cell-content"><?= $block->escapeHtml(__('Found Orphans')) ?></span>
        </th>
        </thead>
        <tbody>
        <?php $i = 0; ?>
        <?php foreach ($tables as $table) : ?>
            <?php $rowClass = ($i % 2 == 0) ? '_odd-row' : ''; ?>
            <tr class="data-row <?= $block->escapeCss($rowClass) ?>">
                <td><?= $block->escapeHtml($table->getTableName()) ?></td>
                <td><?= $block->escapeHtml($viewModel->getTotalsPerTable($table)) ?></td>
                <td><?= $block->escapeHtml($viewModel->getOrphansCountPerTable($table)) ?></td>
            </tr>
            <?php $i++; ?>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
